spring:
  cloud:
    kubernetes:
      discovery:
        namespaces: popi
    gateway:
      routes:
        - id: auth-reissue
          uri: http://auth-svc.popi.svc.cluster.local
          predicates:
            - Path=/auth/reissue
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth/(?<segment>.*), /${segment}
            - RefreshTokenHeaderFilter

        - id: auth-service
          uri: http://auth-svc.popi.svc.cluster.local
          predicates:
            - Path=/auth/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: auth-docs
          uri: http://auth-svc.popi.svc.cluster.local
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth/(?<segment>.*), /${segment}

      globalcors:
        cors-configurations:
          "[/**]":
            allow-credentials: true
            allowed-origins:
              - http://localhost:3000
              - https://www.dev.ceo.popi.today
            allowed-headers:
              - "*"
            allowed-methods:
              - "*"

eureka:
  client:
    enabled: false

springdoc:
  swagger-ui:
    urls[0]:
      name: 인증 서비스
      url: /auth/v3/api-docs

logging:
  level:
    org.hibernate.SQL: debug
