server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/chic2chic/popi-config.git
          default-label: main
          skipSslValidation: true

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics