apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: popi
data:
  application-k8s.yml: |
    spring:
      cloud:
        kubernetes:
          discovery:
            all-namespaces: true
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            format_sql: true
            default_batch_fetch_size: 100
        open-in-view: false
      data:
        redis:
          host: ${REDIS_HOST}
          port: ${REDIS_PORT}
          password: ${REDIS_PASSWORD:}
    
    eureka:
      client:
        enabled: false
    
    logging:
      level:
        org.hibernate.SQL: debug
    
    spring-doc:
      default-consumes-media-type: application/json
      default-produces-media-type: application/json
      swagger-ui:
        tags-sorter: alpha
        operations-sorter: method
        disable-swagger-default-url: true
        path: /swagger-ui
        doc-expansion: none
