server:
  port: 0

spring:
  application:
    name: reservations
  cloud:
    kubernetes:
      config:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${RESERVATION_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      database: 1
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.hibernate.SQL: debug

spring-doc:
  api-docs:
    version: openapi_3_1
    enabled: true
  enable-kotlin: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

resilience4j:
  retry:
    instances:
      redisRetry:
        max-attempts: 5
        wait-duration: 200ms
        retry-exceptions:
          - java.lang.RuntimeException

  circuitbreaker:
    instances:
      redisCircuitBreaker:
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true

manager:
  service:
    name: managers
    url: http://localhost:8080
member:
  service:
    name: members
