spring:
  application:
    name: eureka-server
  cloud:
    config:
      name: ${SPRING_CLOUD_CONFIG_NAME:eureka-server}
  config:
    import: configserver:http://${CONFIG_SERVER_NAME:localhost}:8888